import ComputableAnalysis.RiemannHilbert.LogarithmContinuation

/-! Representation invariance and admissible refinement of constructed
logarithm continuation. Refinement is generated by actual chart subdivision,
not by an assumed equality of logarithm values. -/
namespace ComputableAnalysis.RiemannHilbert.LogarithmContinuation
open ComplexRaw FunctionTheory LocalODE NonzeroBoxSearch
set_option maxHeartbeats 1000000

theorem renamedNonzero (g : Scalar → Scalar) (hg : ∀ z, (g z).val.Equiv z.val)
    (c : Scalar) (hc : Nonzero c) : Nonzero (g c) :=
  (nonzero_congr (g c) c (hg c)).2 hc

def rename (g : Scalar → Scalar) (hg : ∀ z, (g z).val.Equiv z.val)
    {c d : Scalar} {hc : Nonzero c} {hd : Nonzero d} (p : Chain c hc d hd) :
    Chain (g c) (renamedNonzero g hg c hc) (g d) (renamedNonzero g hg d hd) :=
  match p with
  | .nil _ _ => .nil _ _
  | @Chain.step c d e hc hd he hcd tail => .step
      ((RelativeLogarithm.domain_congr c (g c) hc (renamedNonzero g hg c hc) (equiv_symm (hg c))
        d (g d) (equiv_symm (hg d))).1 hcd) (rename g hg tail)

theorem value_rename (g : Scalar → Scalar) (hg : ∀ z, (g z).val.Equiv z.val)
    {c d : Scalar} {hc : Nonzero c} {hd : Nonzero d} (p : Chain c hc d hd)
    (a b : Scalar) (hab : a.val.Equiv b.val) :
    (value p a).val.Equiv (value (rename g hg p) b).val := by
  induction p generalizing a b with
  | nil => exact hab
  | @step c d e hc hd he hcd tail ih =>
      exact ih _ _ (LogarithmBranchCharts.value_congr c (g c) hc (renamedNonzero g hg c hc) a b
        (equiv_symm (hg c)) hab d (g d) hcd _ (equiv_symm (hg d)))

theorem terminal_rename (g : Scalar → Scalar) (hg : ∀ z, (g z).val.Equiv z.val)
    {c d : Scalar} {hc : Nonzero c} {hd : Nonzero d} (p : Chain c hc d hd)
    (a b : Scalar) (hab : a.val.Equiv b.val) (z w : Scalar)
    (hz : (terminalFunction p a).domain z) (hw : (terminalFunction (rename g hg p) b).domain w)
    (hzw : z.val.Equiv w.val) :
    ((terminalFunction p a).eval z hz).val.Equiv ((terminalFunction (rename g hg p) b).eval w hw).val :=
  LogarithmBranchCharts.value_congr d (g d) hd (renamedNonzero g hg d hd) _ _
    (equiv_symm (hg d)) (value_rename g hg p a b hab) z w hz hw hzw

inductive Refines : {c d : Scalar} → {hc : Nonzero c} → {hd : Nonzero d} →
    Chain c hc d hd → Chain c hc d hd → Prop where
  | refl {c d hc hd} (p : Chain c hc d hd) : Refines p p
  | step {c d e hc hd he} (hcd : RelativeLogarithm.domain c hc d)
      {p q : Chain d hd e he} (h : Refines p q) : Refines (.step hcd p) (.step hcd q)
  | subdivide {c d e f hc hd he hf} (hce : RelativeLogarithm.domain c hc e)
      (hcd : RelativeLogarithm.domain c hc d) (hde : RelativeLogarithm.domain d hd e)
      (tail : Chain e he f hf) : Refines (.step hce tail) (.step hcd (.step hde tail))
  | trans {c d hc hd} {p q r : Chain c hc d hd} (hpq : Refines p q) (hqr : Refines q r) : Refines p r

theorem value_refines {c d : Scalar} {hc : Nonzero c} {hd : Nonzero d}
    {p q : Chain c hc d hd} (h : Refines p q) (a : Scalar) :
    (value p a).val.Equiv (value q a).val := by
  induction h generalizing a with
  | refl p => exact equiv_refl _ (value p a).property
  | step hcd h ih => exact ih _
  | subdivide hce hcd hde tail => exact subdivision hce hcd hde tail a
  | @trans c d hc hd p q r hpq hqr ihpq ihqr =>
      exact equiv_trans (value p a).property (value q a).property (value r a).property (ihpq a) (ihqr a)

theorem terminal_refines {c d : Scalar} {hc : Nonzero c} {hd : Nonzero d}
    {p q : Chain c hc d hd} (h : Refines p q) (a : Scalar) (z : Scalar)
    (hz : (terminalFunction p a).domain z) :
    ((terminalFunction p a).eval z hz).val.Equiv ((terminalFunction q a).eval z hz).val :=
  terminal_agreement p q a a (value_refines h a) z z hz hz (equiv_refl _ z.property)

end ComputableAnalysis.RiemannHilbert.LogarithmContinuation
