import ComputableAnalysis.RationalCircle
import ComputableAnalysis.Calculus
import ComputableAnalysis.IdentityInverse
import ComputableAnalysis.ArctanEffectiveFTC
import ComputableAnalysis.IntegralIdentities
import ComputableAnalysis.TurningPointIntegral
import ComputableAnalysis.AbsIntegral
import ComputableAnalysis.PrimitivePiecewiseFTC
import ComputableAnalysis.FiniteFTCIntervalRegular
import ComputableAnalysis.FiniteSinePrefixFTC
import ComputableAnalysis.PolynomialFTCValues
import ComputableAnalysis.FiniteFTCPolynomial
import ComputableAnalysis.SinPiIntegral
import ComputableAnalysis.SinPiTransportSubgoals
import ComputableAnalysis.SinPiTransportAdapter
import ComputableAnalysis.SinPiSquareFTC
import ComputableAnalysis.TangentPullbackEffectiveFTC
import ComputableAnalysis.StableRotationDerivative
import ComputableAnalysis.EffectiveFTCPortfolio
import ComputableAnalysis.MonotonicityConvexity
import ComputableAnalysis.PowerSeries
import ComputableAnalysis.FiniteTaylorFTCInterface
import ComputableAnalysis.FiniteSineIntegral
import ComputableAnalysis.FiniteExponentialTaylor
import ComputableAnalysis.Series
import ComputableAnalysis.FirstYearCalculus
import ComputableAnalysis.FiniteFourierFoundation
import ComputableAnalysis.EffectiveFourierSeries
import ComputableAnalysis.EffectiveFourierTail
import ComputableAnalysis.ExpProofs
import ComputableAnalysis.FiniteGapAwareInverseSearch
import ComputableAnalysis.Logarithm
import ComputableAnalysis.ScalarODEUniqueness
import ComputableAnalysis.PeanoBaker
import ComputableAnalysis.FiniteNBallVolume
import ComputableAnalysis.FiniteGaussianIntegral
import ComputableAnalysis.ComplexCircleBridge
import ComputableAnalysis.ComplexPathIntegral
import ComputableAnalysis.FiniteComplexPathCertificate

/-!
# Computable calculus foundation

This is the focused public entry point for the project's calculus route.  It
collects the rational-circle, finite-integral, effective-FTC, power-series,
exponential/logarithm, Fourier, and scalar/linear-ODE interfaces without
requiring users to import the full benchmark catalogue in `ComputableAnalysis`.

The imports expose certificates and raw algorithms; they do not introduce a
completed real-number or measurable-function foundation.
-/
