import ComputableAnalysis.Basic

/-!
# A finite Pell-equation certificate

The rational recurrence generated by 3 + 2 sqrt(2) produces finite solutions
to x^2 - 2 y^2 = 1.  The recurrence and each requested stage are rational
certificates; no infinite sequence or completed irrational value is used.
-/

namespace ComputableAnalysis

def pellPair : Nat → Rat × Rat
  | 0 => (1, 0)
  | n + 1 =>
      let p := pellPair n
      (3 * p.1 + 4 * p.2, 2 * p.1 + 3 * p.2)

def pellInvariant (p : Rat × Rat) : Prop :=
  p.1 * p.1 - 2 * p.2 * p.2 = 1

structure FinitePellCertificate where
  stage : Nat
  x : Rat
  y : Rat
  pair_eq : (x, y) = pellPair stage
  invariant : pellInvariant (x, y)

theorem pellPair_invariant (stage : Nat) :
    pellInvariant (pellPair stage) := by
  induction stage with
  | zero =>
      change (1 : Rat) * 1 - 2 * 0 * 0 = 1
      native_decide
  | succ stage ih =>
      simp only [pellPair]
      dsimp [pellInvariant] at ih ⊢
      grind [Rat.sub_eq_add_neg, Rat.mul_add, Rat.add_mul,
        Rat.mul_assoc, Rat.mul_comm, Rat.add_assoc, Rat.add_comm]

def finitePellCertificate (stage : Nat) : FinitePellCertificate where
  stage := stage
  x := (pellPair stage).1
  y := (pellPair stage).2
  pair_eq := rfl
  invariant := pellPair_invariant stage

theorem FinitePellCertificate.solution
    (certificate : FinitePellCertificate) :
    certificate.x * certificate.x -
        2 * certificate.y * certificate.y = 1 := by
  exact certificate.invariant

theorem finitePellCertificate_stage_one :
    (finitePellCertificate 1).x = 3 ∧
      (finitePellCertificate 1).y = 2 := by
  constructor
  · native_decide
  · native_decide

theorem finitePellCertificate_stage_two :
    (finitePellCertificate 2).x = 17 ∧
      (finitePellCertificate 2).y = 12 := by
  constructor
  · native_decide
  · native_decide

theorem finitePellCertificate_stage_three :
    (finitePellCertificate 3).x = 99 ∧
      (finitePellCertificate 3).y = 70 := by
  constructor
  · native_decide
  · native_decide

end ComputableAnalysis
