import ComputableAnalysis.PolynomialMeanValue

/-!
# Exact finite derivative data for monomials

The coefficient list is generated by finite recursion, and the theorem
connects its Horner derivative evaluator to the familiar monomial formula.
This is an algebraic certificate for later MVT/FTC consumers, not a theorem
about completed real-valued functions.
-/

namespace ComputableAnalysis

namespace Polynomial

def monomialCoeffs : Nat -> List Rat
  | 0 => [1]
  | n + 1 => 0 :: monomialCoeffs n

theorem eval_monomialCoeffs (n : Nat) (x : Rat) :
    eval (monomialCoeffs n) x = x ^ n := by
  induction n with
  | zero => simp [monomialCoeffs, eval] <;> grind
  | succ n ih =>
      simp only [monomialCoeffs]
      change (0 : Rat) + x * eval (monomialCoeffs n) x = x ^ (n + 1)
      simp only [Rat.zero_add]
      rw [ih]
      rw [Rat.pow_succ]
      grind [Rat.mul_comm]

theorem finiteDerivativeEval_monomialCoeffs_succ (n : Nat) (x : Rat) :
    finiteDerivativeEval (monomialCoeffs (n + 1)) x =
      ((n + 1 : Nat) : Rat) * x ^ n := by
  induction n with
  | zero => simp [monomialCoeffs, finiteDerivativeEval, eval] <;> grind
  | succ n ih =>
      simp only [monomialCoeffs]
      change eval (monomialCoeffs (n + 1)) x +
        x * finiteDerivativeEval (monomialCoeffs (n + 1)) x =
        ((n + 1 + 1 : Nat) : Rat) * x ^ (n + 1)
      rw [eval_monomialCoeffs]
      rw [ih]
      rw [Rat.pow_succ]
      grind [Rat.mul_assoc, Rat.mul_comm, Rat.add_mul, Rat.mul_add]

end Polynomial

end ComputableAnalysis
