import ComputableAnalysis.ComplexInterval

/-!
# Power series over rational complex numbers

The elementary power-series algorithms are developed once for complex numbers.
Real functions are then obtained by restricting to the real axis.
-/

namespace ComputableAnalysis

namespace QComplex

def normBound (z : QComplex) : Rat := qabs z.re + qabs z.im

def inDisk (z : QComplex) (R : Rat) : Prop := normBound z < R

def pow (z : QComplex) : Nat -> QComplex
  | 0 => one
  | n + 1 => mul z (pow z n)

def divRat (z : QComplex) (q : Rat) : QComplex :=
  { re := z.re / q, im := z.im / q }

end QComplex

def factorial : Nat -> Nat
  | 0 => 1
  | n + 1 => (n + 1) * factorial n

def factorialRat (n : Nat) : Rat := (factorial n : Rat)

def seriesFuel (eps : QPos) : Nat := eps.val.den + 8

namespace FormalPowerSeries

/-- Rational coefficient stream for `sum c_n z^n`. -/
abbrev Coeffs := Nat -> Rat

def altSign (k : Nat) : Rat := if k % 2 = 0 then 1 else -1

/-- Formal derivative of a rational coefficient stream. -/
def derivative (c : Coeffs) : Coeffs :=
  fun n => ((n + 1 : Nat) : Rat) * c (n + 1)

def neg (c : Coeffs) : Coeffs :=
  fun n => -c n

def add (c d : Coeffs) : Coeffs :=
  fun n => c n + d n

def scaleRat (r : Rat) (c : Coeffs) : Coeffs :=
  fun n => r * c n

def HasFormalDerivative (F f : Coeffs) : Prop :=
  derivative F = f

/-- Coefficient stream generated by the definite-integral step
`F(x) = F(0) + integral_0^x dF(t) dt`.

This is not an indefinite integral object: the constant term is specified, and
the coefficients are the formal result of integrating over the concrete
interval from `0` to `x`. -/
def coeffsFromDerivativeAtZero (F0 : Rat) (dF : Coeffs) : Coeffs
  | 0 => F0
  | n + 1 => dF n / (((n + 1 : Nat) : Rat))

def monomialCoeff (k : Nat) : Coeffs :=
  fun n => if n = k then 1 else 0

def monomialShiftedCoeff (k : Nat) : Coeffs :=
  fun n => if n = k + 1 then 1 / (((k + 1 : Nat) : Rat)) else 0

/-!
The arctangent facts here are intentionally only the formal coefficient
calculus.

mathlib analogue: the analytic theorem is `Real.hasSum_arctan` and related
power-series/Taylor facts.  Here we keep the finite algebra separate from
convergence and from the geometric branch relation: the theorem below says
that differentiating the odd arctangent monomial coefficients recovers the
geometric-series coefficients for `1/(1+x^2)`.
-/

def atanOddCoeff (k : Nat) : Rat :=
  altSign k / (((2 * k + 1 : Nat) : Rat))

/-- Coefficients of the geometric series for `1/(1+x^2)`:
`1 - x^2 + x^4 - ...`. -/
def oneOverOnePlusSquareCoeff : Coeffs :=
  fun n => if n % 2 = 0 then altSign (n / 2) else 0

/-- Taylor coefficients for the arctangent series generated from
`atan' = 1/(1+x^2)` and `atan(0)=0`.

This definition is intentionally recurrence-shaped: the coefficient of
`x^(n+1)` is the coefficient of `x^n` in `1/(1+x^2)`, divided by `n+1`.
That mirrors the iterated-FTC construction, while staying purely algebraic at
the formal coefficient level. -/
def atanTaylorCoeff : Coeffs :=
  coeffsFromDerivativeAtZero 0 oneOverOnePlusSquareCoeff

def expCoeff : Coeffs :=
  fun n => 1 / factorialRat n

mutual

/-- Sine coefficients, defined by the differential system `sin' = cos`. -/
def sinCoeff : Coeffs
  | 0 => 0
  | n + 1 => cosCoeff n / (((n + 1 : Nat) : Rat))

/-- Cosine coefficients, defined by the differential system `cos' = -sin`. -/
def cosCoeff : Coeffs
  | 0 => 1
  | n + 1 => -sinCoeff n / (((n + 1 : Nat) : Rat))

end

mutual

/-- Hyperbolic sine coefficients, defined by `sinh' = cosh`. -/
def sinhCoeff : Coeffs
  | 0 => 0
  | n + 1 => coshCoeff n / (((n + 1 : Nat) : Rat))

/-- Hyperbolic cosine coefficients, defined by `cosh' = sinh`. -/
def coshCoeff : Coeffs
  | 0 => 1
  | n + 1 => sinhCoeff n / (((n + 1 : Nat) : Rat))

end

theorem factorialRat_succ (n : Nat) :
    factorialRat (n + 1) = ((n + 1 : Nat) : Rat) * factorialRat n := by
  simp [factorialRat, factorial]

theorem factorial_ne_zero : forall n : Nat, factorial n ≠ 0
  | 0 => by simp [factorial]
  | n + 1 => by
      simp [factorial]
      exact Nat.mul_ne_zero (Nat.succ_ne_zero n) (factorial_ne_zero n)

theorem natCast_succ_ne_zero (n : Nat) :
    (((n + 1 : Nat) : Rat) ≠ 0) := by
  exact Rat.ne_of_gt ((Rat.natCast_pos).2 (by omega : 0 < n + 1))

theorem mul_div_cancel_left {a b : Rat} (ha : a ≠ 0) :
    a * (b / a) = b := by
  rw [Rat.div_def]
  calc
    a * (b * a⁻¹) = b * (a * a⁻¹) := by
      grind [Rat.mul_assoc, Rat.mul_comm]
    _ = b * 1 := by
      rw [Rat.mul_inv_cancel a ha]
    _ = b := by
      rw [Rat.mul_one]

theorem coeffsFromDerivativeAtZero_hasFormalDerivative (F0 : Rat) (dF : Coeffs) :
    HasFormalDerivative (coeffsFromDerivativeAtZero F0 dF) dF := by
  unfold HasFormalDerivative
  funext n
  dsimp [derivative, coeffsFromDerivativeAtZero]
  exact mul_div_cancel_left (natCast_succ_ne_zero n)

theorem derivative_neg (c : Coeffs) :
    derivative (neg c) = neg (derivative c) := by
  funext n
  dsimp [derivative, neg]
  rw [Rat.mul_neg]

theorem neg_neg (c : Coeffs) :
    neg (neg c) = c := by
  funext n
  dsimp [neg]
  exact Rat.neg_neg (c n)

theorem derivative_add (c d : Coeffs) :
    derivative (add c d) = add (derivative c) (derivative d) := by
  funext n
  dsimp [derivative, add]
  rw [Rat.mul_add]

theorem derivative_scaleRat (r : Rat) (c : Coeffs) :
    derivative (scaleRat r c) = scaleRat r (derivative c) := by
  funext n
  dsimp [derivative, scaleRat]
  grind [Rat.mul_assoc, Rat.mul_comm]

theorem HasFormalDerivative.add {F f G g : Coeffs}
    (hF : HasFormalDerivative F f) (hG : HasFormalDerivative G g) :
    HasFormalDerivative (add F G) (add f g) := by
  unfold HasFormalDerivative at *
  rw [derivative_add, hF, hG]

theorem HasFormalDerivative.scaleRat (r : Rat) {F f : Coeffs}
    (hF : HasFormalDerivative F f) :
    HasFormalDerivative (scaleRat r F) (scaleRat r f) := by
  unfold HasFormalDerivative at *
  rw [derivative_scaleRat, hF]

theorem monomialShiftedCoeff_derivative (k : Nat) :
    HasFormalDerivative (monomialShiftedCoeff k) (monomialCoeff k) := by
  unfold HasFormalDerivative
  funext n
  dsimp [derivative, monomialShiftedCoeff, monomialCoeff]
  by_cases hn : n = k
  · subst n
    simp
    have hk : ((k : Rat) + 1) ≠ 0 := by
      exact Rat.ne_of_gt (by grind : (0 : Rat) < (k : Rat) + 1)
    exact mul_div_cancel_left hk
  · simp [hn]

/-- Formal arctangent coefficient calculus:
`d/dx ((-1)^k x^(2k+1)/(2k+1)) = (-1)^k x^(2k)`.

This is the term-level brick needed before proving that the arctangent
power-series algorithm agrees with the integral of `1/(1+x^2)`. -/
theorem atanOddCoeff_derivative_term (k : Nat) :
    (((2 * k + 1 : Nat) : Rat)) * atanOddCoeff k = altSign k := by
  unfold atanOddCoeff
  exact mul_div_cancel_left (natCast_succ_ne_zero (2 * k))

/-- The arctangent Taylor coefficient stream differentiates to the geometric
coefficient stream for `1/(1+x^2)`.

This is the formal-series part of the preferred Taylor route:
FTC gives `atan x = atan 0 + integral_0^x 1/(1+t^2) dt`, and repeated FTC on
the geometric-series coefficients gives the odd arctangent coefficients. -/
theorem atanTaylorCoeff_hasFormalDerivative :
    HasFormalDerivative atanTaylorCoeff oneOverOnePlusSquareCoeff :=
  coeffsFromDerivativeAtZero_hasFormalDerivative 0 oneOverOnePlusSquareCoeff

theorem atanTaylorCoeff_zero :
    atanTaylorCoeff 0 = 0 := rfl

theorem atanTaylorCoeff_odd (k : Nat) :
    atanTaylorCoeff (2 * k + 1) = atanOddCoeff k := by
  unfold atanTaylorCoeff coeffsFromDerivativeAtZero oneOverOnePlusSquareCoeff atanOddCoeff
  change ((if (2 * k) % 2 = 0 then altSign ((2 * k) / 2) else 0) /
      (((2 * k) + 1 : Nat) : Rat)) =
    altSign k / (((2 * k + 1 : Nat) : Rat))
  have hmod : (2 * k) % 2 = 0 := by omega
  have hdiv : (2 * k) / 2 = k := by omega
  simp [hmod, hdiv]

theorem atanTaylorCoeff_even_succ (k : Nat) :
    atanTaylorCoeff (2 * k + 2) = 0 := by
  rw [show 2 * k + 2 = (2 * k + 1) + 1 by omega]
  unfold atanTaylorCoeff coeffsFromDerivativeAtZero oneOverOnePlusSquareCoeff
  change ((if (2 * k + 1) % 2 = 0 then altSign ((2 * k + 1) / 2) else 0) /
      (((2 * k + 1) + 1 : Nat) : Rat)) = 0
  have hmod : ¬(2 * k + 1) % 2 = 0 := by omega
  rw [if_neg hmod]
  rw [Rat.div_def]
  simp

/-- The formal derivative of the exponential coefficient stream is itself.

This is the power-series-specific algebraic fact behind the future theorem
that the boxed algorithm `exp.ps` has derivative `exp.ps`. -/
theorem expCoeff_derivative :
    derivative expCoeff = expCoeff := by
  funext n
  dsimp [derivative, expCoeff]
  rw [factorialRat_succ n]
  have hn : (((n + 1 : Nat) : Rat) ≠ 0) := natCast_succ_ne_zero n
  have hf : factorialRat n ≠ 0 := by
    unfold factorialRat
    exact_mod_cast factorial_ne_zero n
  rw [Rat.div_def, Rat.div_def]
  rw [Rat.one_mul, Rat.one_mul]
  grind [Rat.mul_assoc, Rat.mul_comm]

theorem expCoeff_second_derivative :
    derivative (derivative expCoeff) = expCoeff := by
  rw [expCoeff_derivative, expCoeff_derivative]

/-- The formal derivative of the sine coefficient stream is cosine. -/
theorem sinCoeff_derivative :
    derivative sinCoeff = cosCoeff := by
  funext n
  dsimp [derivative]
  rw [sinCoeff]
  exact mul_div_cancel_left (natCast_succ_ne_zero n)

/-- The formal derivative of the cosine coefficient stream is negative sine. -/
theorem cosCoeff_derivative :
    derivative cosCoeff = neg sinCoeff := by
  funext n
  dsimp [derivative, neg]
  rw [cosCoeff]
  exact mul_div_cancel_left (natCast_succ_ne_zero n)

theorem sinCoeff_second_derivative :
    derivative (derivative sinCoeff) = neg sinCoeff := by
  rw [sinCoeff_derivative, cosCoeff_derivative]

theorem cosCoeff_second_derivative :
    derivative (derivative cosCoeff) = neg cosCoeff := by
  rw [cosCoeff_derivative, derivative_neg, sinCoeff_derivative]

/-- The formal derivative of the hyperbolic sine coefficient stream is
hyperbolic cosine. -/
theorem sinhCoeff_derivative :
    derivative sinhCoeff = coshCoeff := by
  funext n
  dsimp [derivative]
  rw [sinhCoeff]
  exact mul_div_cancel_left (natCast_succ_ne_zero n)

/-- The formal derivative of the hyperbolic cosine coefficient stream is
hyperbolic sine. -/
theorem coshCoeff_derivative :
    derivative coshCoeff = sinhCoeff := by
  funext n
  dsimp [derivative]
  rw [coshCoeff]
  exact mul_div_cancel_left (natCast_succ_ne_zero n)

theorem sinhCoeff_second_derivative :
    derivative (derivative sinhCoeff) = sinhCoeff := by
  rw [sinhCoeff_derivative, coshCoeff_derivative]

theorem coshCoeff_second_derivative :
    derivative (derivative coshCoeff) = coshCoeff := by
  rw [coshCoeff_derivative, sinhCoeff_derivative]

/-- First-year calculus table entry: the formal derivative of `exp` is `exp`. -/
theorem expCoeff_hasFormalDerivative :
    HasFormalDerivative expCoeff expCoeff :=
  expCoeff_derivative

/-- First-year calculus table entry: the formal derivative of `sin` is `cos`. -/
theorem sinCoeff_hasFormalDerivative :
    HasFormalDerivative sinCoeff cosCoeff :=
  sinCoeff_derivative

/-- First-year calculus table entry: the formal derivative of `-cos` is `sin`. -/
theorem neg_cosCoeff_hasFormalDerivative :
    HasFormalDerivative (neg cosCoeff) sinCoeff := by
  unfold HasFormalDerivative
  rw [derivative_neg, cosCoeff_derivative, neg_neg]

/-- First-year calculus table entry: the formal derivative of `cosh` is `sinh`. -/
theorem coshCoeff_hasFormalDerivative :
    HasFormalDerivative coshCoeff sinhCoeff :=
  coshCoeff_derivative

/-- First-year calculus table entry: the formal derivative of `sinh` is `cosh`. -/
theorem sinhCoeff_hasFormalDerivative :
    HasFormalDerivative sinhCoeff coshCoeff :=
  sinhCoeff_derivative

end FormalPowerSeries

namespace RationalMajorant

/-- Data used to justify a power-series computation at a point: after `start`,
the coefficient/input terms are dominated by a geometric sequence. -/
structure GeometricCertificate where
  scale : Rat
  ratio : Rat
  start : Nat
  scale_nonneg : 0 <= scale
  ratio_nonneg : 0 <= ratio
  ratio_small : ratio <= (1 : Rat) / 2

def geomTailPartial (C r : Rat) (N : Nat) : Nat -> Rat
  | 0 => 0
  | k + 1 => geomTailPartial C r N k + C * r ^ (N + k)

def geomTailBound (C r : Rat) (N : Nat) : Rat :=
  2 * C * r ^ N

theorem two_mul_half : (2 : Rat) * (1 / 2 : Rat) = 1 := by
  rw [Rat.div_def]
  rw [Rat.one_mul]
  rw [Rat.mul_inv_cancel]
  exact Rat.ne_of_gt ((Rat.natCast_pos).2 (by omega : 0 < (2 : Nat)))

/-- Finite geometric tails with ratio at most `1/2` are bounded by twice
the first omitted majorant term.  This is the rational-only convergence
estimate that later powers `exp`, `sin`, and `cos` certificates. -/
theorem geometric_tail_bound_valid {C r : Rat} {N k : Nat}
    (hC : 0 <= C) (hr0 : 0 <= r) (hrHalf : r <= (1 : Rat) / 2) :
    geomTailPartial C r N k + 2 * C * r ^ (N + k) <= geomTailBound C r N := by
  induction k with
  | zero =>
      simp [geomTailPartial, geomTailBound]
      rw [Rat.zero_add]
      exact Rat.le_refl
  | succ k ih =>
      rw [geomTailPartial]
      have hpowNonneg : 0 <= r ^ (N + k) := Rat.pow_nonneg hr0
      have htermNonneg : 0 <= C * r ^ (N + k) := Rat.mul_nonneg hC hpowNonneg
      have h2pos : (0 : Rat) < 2 := (Rat.natCast_pos).2 (by omega : 0 < (2 : Nat))
      have h2nonneg : 0 <= (2 : Rat) := Rat.le_of_lt h2pos
      have h2rLe : (2 : Rat) * r <= 1 := by
        have hle0 : (2 : Rat) * r <= 2 * (1 / 2 : Rat) :=
          Rat.mul_le_mul_of_nonneg_left hrHalf h2nonneg
        rw [two_mul_half] at hle0
        exact hle0
      have hnext : 2 * C * r ^ (N + (k + 1)) <= C * r ^ (N + k) := by
        rw [show N + (k + 1) = N + k + 1 by omega]
        rw [Rat.pow_succ]
        calc
          2 * C * (r ^ (N + k) * r) = (C * r ^ (N + k)) * (2 * r) := by
            grind [Rat.mul_assoc, Rat.mul_comm]
          _ <= (C * r ^ (N + k)) * 1 :=
            Rat.mul_le_mul_of_nonneg_left h2rLe htermNonneg
          _ = C * r ^ (N + k) := by
            rw [Rat.mul_one]
      calc
        geomTailPartial C r N k + C * r ^ (N + k) + 2 * C * r ^ (N + (k + 1))
            <= geomTailPartial C r N k + C * r ^ (N + k) + C * r ^ (N + k) := by
              rw [Rat.add_le_add_left]
              exact hnext
        _ = geomTailPartial C r N k + 2 * C * r ^ (N + k) := by
          grind [Rat.mul_assoc, Rat.add_assoc]
        _ <= geomTailBound C r N := ih

theorem geometric_tail_partial_bound {C r : Rat} {N k : Nat}
    (hC : 0 <= C) (hr0 : 0 <= r) (hrHalf : r <= (1 : Rat) / 2) :
    geomTailPartial C r N k <= geomTailBound C r N := by
  have hpowNonneg : 0 <= r ^ (N + k) := Rat.pow_nonneg hr0
  have htermNonneg : 0 <= 2 * C * r ^ (N + k) := by
    have h2nonneg : 0 <= (2 : Rat) :=
      Rat.le_of_lt ((Rat.natCast_pos).2 (by omega : 0 < (2 : Nat)))
    exact Rat.mul_nonneg (Rat.mul_nonneg h2nonneg hC) hpowNonneg
  exact Rat.le_trans
    (show geomTailPartial C r N k <= geomTailPartial C r N k + 2 * C * r ^ (N + k) by
      have h := (Rat.add_le_add_left (a := 0) (b := 2 * C * r ^ (N + k))
        (c := geomTailPartial C r N k)).mpr htermNonneg
      rw [Rat.add_zero] at h
      exact h)
    (geometric_tail_bound_valid hC hr0 hrHalf)

theorem certificate_tail_bound (cert : GeometricCertificate) (k : Nat) :
    geomTailPartial cert.scale cert.ratio cert.start k <=
      geomTailBound cert.scale cert.ratio cert.start :=
  geometric_tail_partial_bound cert.scale_nonneg cert.ratio_nonneg cert.ratio_small

end RationalMajorant

namespace ComplexSeries

def expTerm (z : QComplex) (n : Nat) : QComplex :=
  QComplex.divRat (QComplex.pow z n) (factorialRat n)

def expPartial (z : QComplex) (n : Nat) : QComplex :=
  (List.range n).foldl (fun acc k => QComplex.add acc (expTerm z k)) QComplex.zero

def sinSign (k : Nat) : Rat := if k % 2 = 0 then 1 else -1

def sinTerm (z : QComplex) (k : Nat) : QComplex :=
  QComplex.scaleRat (sinSign k)
    (QComplex.divRat (QComplex.pow z (2 * k + 1)) (factorialRat (2 * k + 1)))

def sinPartial (z : QComplex) (n : Nat) : QComplex :=
  (List.range n).foldl (fun acc k => QComplex.add acc (sinTerm z k)) QComplex.zero

def cosTerm (z : QComplex) (k : Nat) : QComplex :=
  QComplex.scaleRat (sinSign k)
    (QComplex.divRat (QComplex.pow z (2 * k)) (factorialRat (2 * k)))

def cosPartial (z : QComplex) (n : Nat) : QComplex :=
  (List.range n).foldl (fun acc k => QComplex.add acc (cosTerm z k)) QComplex.zero

def errorBox (center : QComplex) (eps : QPos) : QBox :=
  { lo := { re := center.re - eps.val, im := center.im - eps.val },
    hi := { re := center.re + eps.val, im := center.im + eps.val } }

def expBoxAt (z : QComplex) (eps : QPos) : QBox :=
  errorBox (expPartial z (seriesFuel eps)) eps

def sinBoxAt (z : QComplex) (eps : QPos) : QBox :=
  errorBox (sinPartial z (seriesFuel eps)) eps

def cosBoxAt (z : QComplex) (eps : QPos) : QBox :=
  errorBox (cosPartial z (seriesFuel eps)) eps

def expCompute (z : ComplexRaw) : Nat -> QBox :=
  fun n =>
    let eps : QPos := if hn : n = 0 then
      { val := 1, property := by native_decide }
    else
      { val := (1 / (n : Rat)), property := one_div_nat_pos (Nat.pos_of_ne_zero hn) }
    expBoxAt ((z.compute n).center) eps

def sinCompute (z : ComplexRaw) : Nat -> QBox :=
  fun n =>
    let eps : QPos := if hn : n = 0 then
      { val := 1, property := by native_decide }
    else
      { val := (1 / (n : Rat)), property := one_div_nat_pos (Nat.pos_of_ne_zero hn) }
    sinBoxAt ((z.compute n).center) eps

def cosCompute (z : ComplexRaw) : Nat -> QBox :=
  fun n =>
    let eps : QPos := if hn : n = 0 then
      { val := 1, property := by native_decide }
    else
      { val := (1 / (n : Rat)), property := one_div_nat_pos (Nat.pos_of_ne_zero hn) }
    cosBoxAt ((z.compute n).center) eps

def expAt (z : QComplex) : Nat -> QBox :=
  expCompute (ComplexRaw.ofQComplex z)

def sinAt (z : QComplex) : Nat -> QBox :=
  sinCompute (ComplexRaw.ofQComplex z)

def cosAt (z : QComplex) : Nat -> QBox :=
  cosCompute (ComplexRaw.ofQComplex z)

/-- Certification target: the explicit exponential series boxes form a valid
complex raw algorithm.  Proving this requires a rational tail bound and a
nesting argument. -/
def ExpCertified (z : ComplexRaw) : Prop :=
  ComplexRaw.Valid { compute := expCompute z }

/-- Certification target for sine. -/
def SinCertified (z : ComplexRaw) : Prop :=
  ComplexRaw.Valid { compute := sinCompute z }

/-- Certification target for cosine. -/
def CosCertified (z : ComplexRaw) : Prop :=
  ComplexRaw.Valid { compute := cosCompute z }

def ExpTailBound : Prop :=
  forall z eps,
    QBox.Overlaps (expBoxAt z eps) (errorBox (expPartial z (seriesFuel eps + 1)) eps)

def SinTailBound : Prop :=
  forall z eps,
    QBox.Overlaps (sinBoxAt z eps) (errorBox (sinPartial z (seriesFuel eps + 1)) eps)

def CosTailBound : Prop :=
  forall z eps,
    QBox.Overlaps (cosBoxAt z eps) (errorBox (cosPartial z (seriesFuel eps + 1)) eps)

end ComplexSeries

namespace RealSeries

def restrictRealAt (f : QComplex -> Nat -> QBox) (x : Rat) (n : Nat) : QInterval :=
  let B := f (QComplex.ofRat x) n
  { lo := B.lo.re, hi := B.hi.re }

def expCompute (x : Rat) (n : Nat) : QInterval :=
  restrictRealAt ComplexSeries.expAt x n

def sinCompute (x : Rat) (n : Nat) : QInterval :=
  restrictRealAt ComplexSeries.sinAt x n

def cosCompute (x : Rat) (n : Nat) : QInterval :=
  restrictRealAt ComplexSeries.cosAt x n

def expFunRaw : RealFunRaw where
  compute := expCompute

def sinFunRaw : RealFunRaw where
  compute := sinCompute

def cosFunRaw : RealFunRaw where
  compute := cosCompute

def ExpCertified : Prop := expFunRaw.Valid
def SinCertified : Prop := sinFunRaw.Valid
def CosCertified : Prop := cosFunRaw.Valid

def ExpConverges : Prop :=
  ComplexSeries.ExpTailBound /\ ExpCertified

def SinConverges : Prop :=
  ComplexSeries.SinTailBound /\ SinCertified

def CosConverges : Prop :=
  ComplexSeries.CosTailBound /\ CosCertified

end RealSeries

/-- Arctangent from its alternating power series. -/
def arctan (x : Rat) : RealRaw where
  compute := fun n =>
    let y := qabs x
    let state : Rat × Rat := Id.run do
      let mut lo : Rat := 0
      let mut hi : Rat := y
      let mut yPow : Rat := y * y * y
      for i in List.range n do
        let term1 : Rat := yPow / (4 * i + 3)
        yPow := yPow * y * y
        let term2 : Rat := yPow / (4 * i + 5)
        yPow := yPow * y * y
        lo := hi - term1
        hi := lo + term2
      return (lo, hi)
    if 0 <= x then
      { lo := state.1, hi := state.2 }
    else
      { lo := -state.2, hi := -state.1 }

/-- Table-facing name for the arctangent power-series evaluator.

The older proofs keep the shorter name `arctan`; this alias makes explicit that
this construction is the alternating power-series arctangent, distinct from the
geometric and integral arctangent constructions. -/
def arctanSeries (x : Rat) : RealRaw :=
  arctan x

end ComputableAnalysis
