import ComputableAnalysis.IntegralIdentities

/-!
# The half-interval integral of `sin (pi * x)`

This file is the proof-facing entry point for the first nontrivial
trigonometric integral.  The circle layer uses normalized quarter-turns: its
input `t` denotes the angle `t * pi / 2`.  Consequently the requested
function `sin (pi * x)` is obtained at a rational input by evaluating the
circle sine at `2 * x`; no real-valued argument and no primitive real `pi` are
used by the evaluator.

The final equality is intentionally expressed through an effective FTC
certificate.  The certificate is where the finite interval bounds,
monotonicity/turning-point analysis, and endpoint calculation belong.  This
keeps the theorem constructive: the dyadic integral algorithm is a raw
algorithm, while the FTC certificate identifies its value.
-/

namespace ComputableAnalysis

namespace RationalCircle

namespace GeometricTrig

/-- The normalized circle sine reparameterized as `sin (pi * x)`.

The input is rational and is only interpreted through the quarter-turn
parameter `2*x`.  In particular, this definition does not ask for a real
number named `pi` at a rational input.
-/
def sinPiRawOfConstruction
    (C : FunctionRawConstruction)
    (hdefined : forall x, 0 <= x -> x <= (1 : Rat) / 2 ->
      C.sinFunctionRaw.definedAt (2 * x)) :
    PartialRealFunRaw where
  definedAt := fun x => 0 <= x /\ x <= (1 : Rat) / 2
  compute := fun x hx n =>
    C.sinFunctionRaw.compute (2 * x) (hdefined x hx.1 hx.2) n

theorem sinPiRawOfConstruction_valid
    (C : FunctionRawConstruction)
    (hdefined : forall x, 0 <= x -> x <= (1 : Rat) / 2 ->
      C.sinFunctionRaw.definedAt (2 * x)) :
    forall x hx,
      RealRaw.ValidCompute
        ((sinPiRawOfConstruction C hdefined).compute x hx) := by
  intro x hx
  exact C.sinFunctionRaw_valid (2 * x) (hdefined x hx.1 hx.2)

end GeometricTrig

end RationalCircle

namespace SinPiIntegral

open RationalCircle.GeometricTrig

/-!
## Executable dyadic inverse traces

The inverse step is not a classical inverse-function axiom.  A concrete
search records one left/right decision at each stage.  The interval itself is
then generated by rational midpoint arithmetic; the only analytic field is
that the forward interval image overlaps the requested target.
-/

/-- The rational interval selected by a finite left/right bisection path. -/
def dyadicCell (a b : Rat) (path : Nat -> Bool) : Nat -> QInterval
  | 0 => { lo := a, hi := b }
  | n + 1 =>
      let previous := dyadicCell a b path n
      let midpoint := (previous.lo + previous.hi) / 2
      if path n then
        { lo := previous.lo, hi := midpoint }
      else
        { lo := midpoint, hi := previous.hi }

/-- A fully executable inverse trace for a monotone interval branch.

`path` is the actual finite search trace.  `value_overlaps` is the one
function-specific obligation: the forward interval image of every selected
cell must overlap the target box.  The remaining fields ensure that this
trace is a valid shrinking raw interval and stays in the source branch.
-/
structure DyadicInverseTrace
    (I : InvertibleFunctionOnInterval)
    (y : InRangeRaw I) where
  path : Nat -> Bool
  cell_valid : RealRaw.ValidCompute (dyadicCell I.function.lower I.function.upper path)
  cell_in_source : forall n,
    subintervalOf
      (dyadicCell I.function.lower I.function.upper path n)
      I.function.lower I.function.upper
  value_overlaps : forall n,
    QInterval.Overlaps
      (I.continuous.regular.evalInterval
        (dyadicCell I.function.lower I.function.upper path n)
        (cell_in_source n) n)
      (y.value.compute n)

/-- Turn an executable dyadic trace into the inverse-search interface. -/
def DyadicInverseTrace.toSearch
    {I : InvertibleFunctionOnInterval} {y : InRangeRaw I}
    (h : DyadicInverseTrace I y) : InverseBisectionSearch I y where
  compute_preimage := dyadicCell I.function.lower I.function.upper h.path
  valid_preimage := h.cell_valid
  preimage_subinterval := h.cell_in_source
  value_overlaps := h.value_overlaps

theorem DyadicInverseTrace.toSearch_compute_preimage
    {I : InvertibleFunctionOnInterval} {y : InRangeRaw I}
    (h : DyadicInverseTrace I y) (n : Nat) :
    (h.toSearch.compute_preimage n) =
      dyadicCell I.function.lower I.function.upper h.path n :=
  rfl

/-- The arctangent inverse package obtained once every target has an
executable dyadic trace.  This is the exact assembly point for the
arctangent-defined sine construction: no choice of an inverse is taken. -/
def arctanInverseBisectionOfDyadicTraces
    (branch : InvertibleFunctionOnInterval)
    (branch_is_geometric : branch.function =
      IntegralIdentities.arctanGeomOnUnit)
    (targetAt : forall t : RationalCircle.GeometricTrig.QuarterTurn,
      RationalCircle.GeometricTrig.firstQuadrantBranch t -> InRangeRaw branch)
    (targetAt_equiv_halfQuarterTurn :
      forall t ht, (targetAt t ht).value.Equiv
        (RationalCircle.GeometricTrig.halfQuarterTurnRaw t))
    (traceAt : forall y : InRangeRaw branch,
      DyadicInverseTrace branch y) :
    IntegralIdentities.ArctanInverseBisection where
  branch := branch
  branch_is_geometric := branch_is_geometric
  targetAt := targetAt
  targetAt_equiv_halfQuarterTurn := targetAt_equiv_halfQuarterTurn
  bisectionAt := fun y => (traceAt y).toSearch

/-- The rational circle parametrization used after the inverse-arctangent
search.  For a half-angle slope `u`, its imaginary coordinate is
`2*u/(1+u^2)`. -/
def rationalCircleSin (u : Rat) : Rat :=
  (2 * u) / (1 + u * u)

def rationalCircleSinInterval (U : QInterval) : QInterval :=
  { lo := rationalCircleSin U.lo, hi := rationalCircleSin U.hi }

private theorem rationalCircleSin_den_pos {u : Rat} (hu : 0 <= u) :
    0 < 1 + u * u := by
  have hsq : 0 <= u * u := Rat.mul_nonneg hu hu
  grind

private theorem rat_eq_of_mul_eq_mul_pos_local {a b c : Rat}
    (hc : 0 < c) (h : a * c = b * c) : a = b := by
  have hcne : c ≠ 0 := Rat.ne_of_gt hc
  calc
    a = (a * c) * c⁻¹ := by
      have hcancel : c * c⁻¹ = 1 := Rat.mul_inv_cancel c hcne
      grind [Rat.mul_assoc, Rat.mul_comm]
    _ = (b * c) * c⁻¹ := by rw [h]
    _ = b := by
      have hcancel : c * c⁻¹ = 1 := Rat.mul_inv_cancel c hcne
      grind [Rat.mul_assoc, Rat.mul_comm]

private theorem rationalCircleSin_sub_formula {a b : Rat}
    (ha : 0 <= a) (hb : 0 <= b) :
    rationalCircleSin b - rationalCircleSin a =
      (2 * (b - a) * (1 - a * b)) /
        ((1 + a * a) * (1 + b * b)) := by
  let da : Rat := 1 + a * a
  let db : Rat := 1 + b * b
  have hda : 0 < da := by
    dsimp [da]
    exact rationalCircleSin_den_pos ha
  have hdb : 0 < db := by
    dsimp [db]
    exact rationalCircleSin_den_pos hb
  have hprod : 0 < da * db := Rat.mul_pos hda hdb
  apply rat_eq_of_mul_eq_mul_pos_local (c := da * db) hprod
  unfold rationalCircleSin
  rw [Rat.div_def, Rat.div_def, Rat.div_def]
  have hda_ne : da ≠ 0 := Rat.ne_of_gt hda
  have hdb_ne : db ≠ 0 := Rat.ne_of_gt hdb
  have hda_cancel : da⁻¹ * da = 1 := Rat.inv_mul_cancel da hda_ne
  have hdb_cancel : db⁻¹ * db = 1 := Rat.inv_mul_cancel db hdb_ne
  have hleft :
      (2 * b * db⁻¹ - 2 * a * da⁻¹) * (da * db) =
        2 * b * da - 2 * a * db := by
    calc
      (2 * b * db⁻¹ - 2 * a * da⁻¹) * (da * db) =
            (2 * b * db⁻¹) * (da * db) -
            (2 * a * da⁻¹) * (da * db) := by
              grind [Rat.sub_eq_add_neg, Rat.add_mul]
      _ = 2 * b * da - 2 * a * db := by
        have h1 : (2 * b * db⁻¹) * (da * db) = 2 * b * da := by
          calc
            (2 * b * db⁻¹) * (da * db) =
                2 * b * da * (db⁻¹ * db) := by
                  grind [Rat.mul_assoc, Rat.mul_comm]
            _ = 2 * b * da := by rw [hdb_cancel, Rat.mul_one]
        have h2 : (2 * a * da⁻¹) * (da * db) = 2 * a * db := by
          calc
            (2 * a * da⁻¹) * (da * db) =
                2 * a * db * (da⁻¹ * da) := by
                  grind [Rat.mul_assoc, Rat.mul_comm]
            _ = 2 * a * db := by rw [hda_cancel, Rat.mul_one]
        rw [h1, h2]
  have hright :
      (2 * (b - a) * (1 - a * b) * (da * db)⁻¹) * (da * db) =
        2 * (b - a) * (1 - a * b) := by
    calc
      (2 * (b - a) * (1 - a * b) * (da * db)⁻¹) * (da * db) =
          2 * (b - a) * (1 - a * b) *
            ((da * db)⁻¹ * (da * db)) := by
              grind [Rat.mul_assoc, Rat.mul_comm]
      _ = 2 * (b - a) * (1 - a * b) := by
        have hcancel : (da * db)⁻¹ * (da * db) = 1 :=
          Rat.inv_mul_cancel (da * db) (Rat.ne_of_gt hprod)
        rw [hcancel, Rat.mul_one]
  rw [hleft, hright]
  dsimp [da, db]
  grind [Rat.mul_assoc, Rat.mul_comm, Rat.mul_add, Rat.add_mul,
    Rat.sub_eq_add_neg]

private theorem rationalCircleSin_mono {a b : Rat}
    (ha : 0 <= a) (hab : a <= b) (hb : b <= 1) :
    rationalCircleSin a <= rationalCircleSin b := by
  have hb0 : 0 <= b := Rat.le_trans ha hab
  have hprod : a * b <= 1 := by
    have h1 := Rat.mul_le_mul_of_nonneg_right hb ha
    have h2 := Rat.mul_le_mul_of_nonneg_left hab (Rat.le_of_lt (by native_decide : (0 : Rat) < 1))
    grind
  have hba : 0 <= b - a := by grind
  have hnum : 0 <= 2 * (b - a) * (1 - a * b) := by
    exact Rat.mul_nonneg
      (Rat.mul_nonneg (by native_decide) hba) (by grind)
  have hden : 0 < (1 + a * a) * (1 + b * b) :=
    Rat.mul_pos (rationalCircleSin_den_pos ha)
      (rationalCircleSin_den_pos hb0)
  have hdiff : 0 <= rationalCircleSin b - rationalCircleSin a := by
    rw [rationalCircleSin_sub_formula ha hb0, Rat.div_def]
    exact Rat.mul_nonneg hnum (Rat.le_of_lt ((Rat.inv_pos).2 hden))
  grind [Rat.sub_eq_add_neg]

private theorem rationalCircleSin_width_le {a b : Rat}
    (ha : 0 <= a) (hab : a <= b) (hb : b <= 1) :
    rationalCircleSin b - rationalCircleSin a <= 2 * (b - a) := by
  have hb0 : 0 <= b := Rat.le_trans ha hab
  have hba : 0 <= b - a := by grind
  have habprod : a * b <= 1 := by
    have h := Rat.mul_le_mul_of_nonneg_right hb ha
    grind
  have hden : 0 < (1 + a * a) * (1 + b * b) :=
    Rat.mul_pos (rationalCircleSin_den_pos ha)
      (rationalCircleSin_den_pos hb0)
  have hden_one : 1 <= (1 + a * a) * (1 + b * b) := by
    have haa : 0 <= a * a := Rat.mul_nonneg ha ha
    have hbb : 0 <= b * b := Rat.mul_nonneg hb0 hb0
    have hsum : 0 <= a * a + b * b + (a * a) * (b * b) := by
      exact Rat.add_nonneg (Rat.add_nonneg haa hbb)
        (Rat.mul_nonneg haa hbb)
    grind [Rat.mul_add, Rat.add_mul]
  rw [rationalCircleSin_sub_formula ha hb0]
  apply Rat.le_of_mul_le_mul_right (c :=
    (1 + a * a) * (1 + b * b))
  · rw [Rat.div_def]
    let D : Rat := (1 + a * a) * (1 + b * b)
    let N : Rat := 2 * (b - a) * (1 - a * b)
    have hD : D = (1 + a * a) * (1 + b * b) := rfl
    have hcancel : D⁻¹ * D = 1 :=
      Rat.inv_mul_cancel D (Rat.ne_of_gt hden)
    have hNnonneg : 0 <= N := by
      dsimp [N]
      exact Rat.mul_nonneg (Rat.mul_nonneg (by native_decide) hba) (by grind)
    have hNle : N <= 2 * (b - a) := by
      dsimp [N]
      have hp : 0 <= a * b := Rat.mul_nonneg ha hb0
      have hfactor : 1 - a * b <= 1 := by
        grind only [Rat.sub_eq_add_neg]
      exact (by
        calc
          2 * (b - a) * (1 - a * b) <=
              2 * (b - a) * 1 := by
            exact Rat.mul_le_mul_of_nonneg_left hfactor
              (Rat.mul_nonneg (by native_decide) hba)
          _ = 2 * (b - a) := by simp)
    calc
      (N * D⁻¹) * D = N := by
        rw [Rat.mul_assoc, hcancel, Rat.mul_one]
      _ <= 2 * (b - a) * 1 := by simpa using hNle
      _ <= 2 * (b - a) * D := by
        exact Rat.mul_le_mul_of_nonneg_left hden_one
          (Rat.mul_nonneg (by native_decide) hba)
  · exact hden

private theorem rationalCircleSinInterval_valid
    (u : Nat -> QInterval)
    (hu : RealRaw.ValidCompute u)
    (hubounds : forall n, 0 <= (u n).lo /\ (u n).hi <= 1) :
    RealRaw.ValidCompute (fun n => rationalCircleSinInterval (u n)) := by
  constructor
  · intro n
    have horder : (u n).lo <= (u n).hi := by
      have := hu.1 n
      grind [QInterval.width]
    have hmono := rationalCircleSin_mono
      (hubounds n).1 horder (hubounds n).2
    change rationalCircleSin (u n).hi - rationalCircleSin (u n).lo >= 0
    grind
  constructor
  · intro n m hnm
    have hn := hu.2.1 n m hnm
    have hnl := hubounds n
    have hml := hubounds m
    have hlo := rationalCircleSin_mono hnl.1 hn.1
      (Rat.le_trans hn.2.1 hml.2)
    have hmid := rationalCircleSin_mono hml.1 hn.2.1 hml.2
    have hhi := rationalCircleSin_mono
      (Rat.le_trans hml.1 hn.2.1) hn.2.2 hnl.2
    exact ⟨hlo, hmid, hhi⟩
  · intro eps
    have htwo_pos : 0 < (2 : Rat) := by native_decide
    let half : QPos := ⟨eps.val / 2, by
      rw [Rat.div_def]
      exact Rat.mul_pos eps.property ((Rat.inv_pos).2 htwo_pos)⟩
    obtain ⟨N, hN⟩ := hu.2.2 half
    refine ⟨N, ?_⟩
    intro n hn
    have horder : (u n).lo <= (u n).hi := by
      have := hu.1 n
      grind [QInterval.width]
    have hw := rationalCircleSin_width_le
      (hubounds n).1 horder (hubounds n).2
    have hsmall := hN n hn
    have hscaled := Rat.mul_le_mul_of_nonneg_left hsmall
      (by native_decide : (0 : Rat) <= 2)
    change rationalCircleSin (u n).hi - rationalCircleSin (u n).lo <= eps.val
    have hhalf : 2 * half.val = eps.val := by
      dsimp [half]
      rw [Rat.div_def]
      have htwo : (2 : Rat) ≠ 0 := by native_decide
      grind [Rat.mul_assoc, Rat.mul_comm]
    calc
      rationalCircleSin (u n).hi - rationalCircleSin (u n).lo <=
          2 * ((u n).hi - (u n).lo) := hw
      _ <= 2 * half.val := hscaled
      _ = eps.val := hhalf

/-- `sin(pi*x)` from the arctangent inverse, on rational `x` in `[0,1/2]`.

The computation first recovers the half-angle slope by certified bisection,
then applies the rational circle formula. -/
def sinPiRawOfArctan
    (B : IntegralIdentities.ArctanInverseBisection)
    (x : Rat)
    (hx : 0 <= x /\ x <= (1 : Rat) / 2) : RealRaw where
  compute := fun n =>
    rationalCircleSinInterval
      ((B.tangentRaw.compute (2 * x)
        (by
          change RationalCircle.GeometricTrig.firstQuadrantBranch (2 * x)
          constructor
          · exact Rat.mul_nonneg (by native_decide) hx.1
          · have h := Rat.mul_le_mul_of_nonneg_left hx.2 (by native_decide : (0 : Rat) <= 2)
            have hhalf : (2 : Rat) * (1 / 2) = 1 := by native_decide
            rw [hhalf] at h
            exact h) n))

/-- The arctangent-backed pointwise sine evaluator.  The validity field is
the finite interval proof that the monotone rational formula transports the
inverse boxes. -/
structure ArctanSinPiConstruction where
  inverse : IntegralIdentities.ArctanInverseBisection
  sin_valid : forall x hx,
    RealRaw.ValidCompute
      ((sinPiRawOfArctan inverse x hx).compute)

/-- Build the sine construction from the inverse search and its finite
first-quadrant range proof.  The validity of the circle-coordinate evaluator
is discharged by `rationalCircleSinInterval_valid`; it is not an additional
analytic axiom. -/
def ArctanSinPiConstruction.ofInverse
    (B : IntegralIdentities.ArctanInverseBisection)
    (slope_bounded : forall x (hx : 0 <= x /\ x <= (1 : Rat) / 2) n,
      0 <= (B.tangentRaw.compute (2 * x)
        (by
          change RationalCircle.GeometricTrig.firstQuadrantBranch (2 * x)
          constructor
          · exact Rat.mul_nonneg (by native_decide) hx.1
          · have h := Rat.mul_le_mul_of_nonneg_left hx.2
              (by native_decide : (0 : Rat) <= 2)
            have hhalf : (2 : Rat) * (1 / 2) = 1 := by native_decide
            rw [hhalf] at h
            exact h) n).lo /\
      (B.tangentRaw.compute (2 * x)
        (by
          change RationalCircle.GeometricTrig.firstQuadrantBranch (2 * x)
          constructor
          · exact Rat.mul_nonneg (by native_decide) hx.1
          · have h := Rat.mul_le_mul_of_nonneg_left hx.2
              (by native_decide : (0 : Rat) <= 2)
            have hhalf : (2 : Rat) * (1 / 2) = 1 := by native_decide
            rw [hhalf] at h
            exact h) n).hi <= 1) :
    ArctanSinPiConstruction where
  inverse := B
  sin_valid := by
    intro x hx
    apply rationalCircleSinInterval_valid
    · exact B.tangentRaw_valid (2 * x) _
    · exact slope_bounded x hx

theorem arctanInverse_slope_bounded
    (B : IntegralIdentities.ArctanInverseBisection)
    (x : Rat) (hx : 0 <= x /\ x <= (1 : Rat) / 2) (n : Nat) :
    0 <= (B.tangentRaw.compute (2 * x)
      (by
        change RationalCircle.GeometricTrig.firstQuadrantBranch (2 * x)
        constructor
        · exact Rat.mul_nonneg (by native_decide) hx.1
        · have h := Rat.mul_le_mul_of_nonneg_left hx.2
            (by native_decide : (0 : Rat) <= 2)
          have hhalf : (2 : Rat) * (1 / 2) = 1 := by native_decide
          rw [hhalf] at h
          exact h) n).lo /\
      (B.tangentRaw.compute (2 * x)
        (by
          change RationalCircle.GeometricTrig.firstQuadrantBranch (2 * x)
          constructor
          · exact Rat.mul_nonneg (by native_decide) hx.1
          · have h := Rat.mul_le_mul_of_nonneg_left hx.2
              (by native_decide : (0 : Rat) <= 2)
            have hhalf : (2 : Rat) * (1 / 2) = 1 := by native_decide
            rw [hhalf] at h
            exact h) n).hi <= 1 := by
  let ht : RationalCircle.GeometricTrig.firstQuadrantBranch (2 * x) := by
    change 0 <= 2 * x /\ 2 * x <= 1
    constructor
    · exact Rat.mul_nonneg (by native_decide) hx.1
    · have h := Rat.mul_le_mul_of_nonneg_left hx.2
        (by native_decide : (0 : Rat) <= 2)
      have hhalf : (2 : Rat) * (1 / 2) = 1 := by native_decide
      rw [hhalf] at h
      exact h
  have hs := B.tangentAt_stays_in_unitSlope (2 * x) ht n
  change 0 <= ((B.tangentAt (2 * x) ht).compute n).lo /\
    ((B.tangentAt (2 * x) ht).compute n).hi <= 1
  exact ⟨hs.1, hs.2.2⟩

def ArctanSinPiConstruction.canonical
    (B : IntegralIdentities.ArctanInverseBisection) :
    ArctanSinPiConstruction :=
  ArctanSinPiConstruction.ofInverse B
    (fun x hx n => arctanInverse_slope_bounded B x hx n)

/-- Package the arctangent-backed evaluator as the interval function consumed
by the equal-dyadic integral operator. -/
def ArctanSinPiConstruction.onHalf
    (S : ArctanSinPiConstruction) : FunctionOnInterval where
  raw := {
    definedAt := fun x => 0 <= x /\ x <= (1 : Rat) / 2
    compute := fun x hx => (sinPiRawOfArctan S.inverse x hx).compute
  }
  lower := 0
  upper := (1 : Rat) / 2
  defined_on := fun _ hx => hx
  valid_on := by
    intro x hx
    exact S.sin_valid x hx

def ArctanSinPiConstruction.halfIntegral
    (S : ArctanSinPiConstruction)
    (c : Integral.Construction S.onHalf.toRealFunRaw 0 ((1 : Rat) / 2)) : RealRaw :=
  Integral.integral S.onHalf.toRealFunRaw 0 ((1 : Rat) / 2) c

theorem ArctanSinPiConstruction.halfIntegral_valid
    (S : ArctanSinPiConstruction)
    (c : Integral.Construction S.onHalf.toRealFunRaw 0 ((1 : Rat) / 2)) :
    (S.halfIntegral c).Valid := by
  exact FTC.integral_valid_of_construction c

/-- Static-dyadic FTC bridge for the arctangent-backed sine evaluator.

This is the final theorem-facing assembly point: a primitive `F`, a finite
static-dyadic FTC certificate, and the endpoint schedule agreement identify
the actual equal-dyadic integral with `F(1/2)-F(0)`. -/
theorem ArctanSinPiConstruction.halfIntegral_equiv_endpoint_of_staticFTC
    (S : ArctanSinPiConstruction)
    (F : RealFunRaw)
    (h : StaticDyadicEffectiveFTC F S.onHalf.toRealFunRaw
      0 ((1 : Rat) / 2))
    (c : Integral.Construction S.onHalf.toRealFunRaw 0 ((1 : Rat) / 2))
    (hplan : c.plan = FTC.integralPlanOfStaticDyadicEffectiveFTC h)
    (endpoint : FTC.EndpointScheduleAgreement F 0 ((1 : Rat) / 2)
      (FTC.endpointRawOfEffectiveFTC h.toEffectiveFTC)) :
    (S.halfIntegral c).Equiv
      (endpointDifferenceRaw F 0 ((1 : Rat) / 2) endpoint.endpoint_valid) := by
  exact FTC.staticDyadicEffectiveFTC_definiteIntegralEqualsEndpoint_of_endpointAgreement
    h c hplan endpoint

theorem rationalCircleSinInterval_formula (U : QInterval) :
    rationalCircleSinInterval U =
      { lo := rationalCircleSin U.lo, hi := rationalCircleSin U.hi } :=
  rfl

/-- `sin (pi*x)` as a function on the rational interval `[0,1/2]`. -/
def sinPiOnHalf
    (C : FunctionRawConstruction)
    (hdefined : forall x, 0 <= x -> x <= (1 : Rat) / 2 ->
      C.sinFunctionRaw.definedAt (2 * x)) :
    FunctionOnInterval where
  raw := sinPiRawOfConstruction C hdefined
  lower := 0
  upper := (1 : Rat) / 2
  defined_on := by
    intro x hx
    exact hx
  valid_on := by
    intro x hx
    exact sinPiRawOfConstruction_valid C hdefined x hx

/-- The equal-dyadic-subdivision integral of `sin (pi*x)` on `[0,1/2]`.

The caller supplies the usual interval-sum certificate.  This is the
computable value before any identification with a closed expression.
-/
def halfIntegral
    (C : FunctionRawConstruction)
    (hdefined : forall x, 0 <= x -> x <= (1 : Rat) / 2 ->
      C.sinFunctionRaw.definedAt (2 * x))
    (c : Integral.Construction
      (sinPiOnHalf C hdefined).toRealFunRaw 0 ((1 : Rat) / 2)) : RealRaw :=
  Integral.integral
    (sinPiOnHalf C hdefined).toRealFunRaw 0 ((1 : Rat) / 2) c

theorem halfIntegral_valid
    (C : FunctionRawConstruction)
    (hdefined : forall x, 0 <= x -> x <= (1 : Rat) / 2 ->
      C.sinFunctionRaw.definedAt (2 * x))
    (c : Integral.Construction
      (sinPiOnHalf C hdefined).toRealFunRaw 0 ((1 : Rat) / 2)) :
    (halfIntegral C hdefined c).Valid := by
  exact FTC.integral_valid_of_construction c

/--
The exact reusable conclusion of the elementary sine-integral argument.

`F` is the computable primitive (normally the represented function
`-cos(pi*x)/pi`) and `hftc` is an effective, static-dyadic FTC certificate
for its derivative, which is the `sinPiOnHalf` evaluator.  The theorem does
not invoke Mathlib's real numbers: equality is `RealRaw.Equiv`, and the
certificate is made from finite rational interval computations.

The endpoint raw is deliberately returned by the theorem.  Once the
project's reciprocal-`pi` representation is connected to the endpoint, the
same theorem immediately yields the familiar notation
`integral = 1/pi`; the scaled form `pi * integral = 1` is obtained from the
corresponding endpoint identity without changing the integral algorithm.
-/
structure HalfIntegralFTCCertificate
    (C : FunctionRawConstruction)
    (hdefined : forall x, 0 <= x -> x <= (1 : Rat) / 2 ->
      C.sinFunctionRaw.definedAt (2 * x)) where
  primitive : RealFunRaw
  primitive_valid : primitive.Valid
  endpoint_valid :
    RealRaw.ValidCompute
      (endpointDifferenceCompute primitive 0 ((1 : Rat) / 2))
  integral : Integral.Construction
    (sinPiOnHalf C hdefined).toRealFunRaw 0 ((1 : Rat) / 2)
  /-- The integral is computed by the project's fixed equal-dyadic plan. -/
  integral_plan : integral.plan = Integral.staticDyadicPlan
  ftc : DefiniteIntegralEqualsEndpointDifference
    primitive (sinPiOnHalf C hdefined).toRealFunRaw 0 ((1 : Rat) / 2)
    integral endpoint_valid

theorem halfIntegral_equiv_endpoint
    {C : FunctionRawConstruction}
    {hdefined : forall x, 0 <= x -> x <= (1 : Rat) / 2 ->
      C.sinFunctionRaw.definedAt (2 * x)}
    (h : HalfIntegralFTCCertificate C hdefined) :
    (halfIntegral C hdefined h.integral).Equiv
      (endpointDifferenceRaw h.primitive 0 ((1 : Rat) / 2) h.endpoint_valid) :=
  h.ftc

end SinPiIntegral

end ComputableAnalysis
