import ComputableAnalysis.ModularForms.NomeMomentPrefixLinearity

/-! Exact cubic, quartic, and quintic difference-prefix expansions. -/
namespace ComputableAnalysis.ModularForms
open ComplexRaw RiemannHilbert FunctionTheory

theorem representedBlock_add (t u : Nat → ComplexRaw)
    (ht : ∀ n, (t n).Valid) (hu : ∀ n, (u n).Valid) (M N : Nat) :
    (ScalarSeries.block (fun n => add (t n) (u n)) M N).Equiv
      (add (ScalarSeries.block t M N) (ScalarSeries.block u M N)) := by
  induction N with
  | zero =>
    apply ComplexRawQuotient.equiv_of_ofRaw_eq
      (hleft := ScalarSeries.block_valid _ (fun n => add_valid (ht n) (hu n)) M 0)
      (hright := add_valid (ScalarSeries.block_valid t ht M 0) (ScalarSeries.block_valid u hu M 0))
    change (0:ComplexRawQuotient.Value)=0+0
    grind only
  | succ N ih =>
    have h := ComplexRawQuotient.ofRaw_eq_ofRaw
      (hleft := ScalarSeries.block_valid _ (fun n => add_valid (ht n) (hu n)) M N)
      (hright := add_valid (ScalarSeries.block_valid t ht M N) (ScalarSeries.block_valid u hu M N)) ih
    apply ComplexRawQuotient.equiv_of_ofRaw_eq
      (hleft := ScalarSeries.block_valid _ (fun n => add_valid (ht n) (hu n)) M (N+1))
      (hright := add_valid (ScalarSeries.block_valid t ht M (N+1)) (ScalarSeries.block_valid u hu M (N+1)))
    simp only [ScalarSeries.block.eq_2]
    let S := ComplexRawQuotient.ofRaw (ScalarSeries.block (fun n => add (t n) (u n)) M N)
      (ScalarSeries.block_valid _ (fun n => add_valid (ht n) (hu n)) M N)
    let T := ComplexRawQuotient.ofRaw (ScalarSeries.block t M N) (ScalarSeries.block_valid t ht M N)
    let U := ComplexRawQuotient.ofRaw (ScalarSeries.block u M N) (ScalarSeries.block_valid u hu M N)
    let A := ComplexRawQuotient.ofRaw (t (M+N)) (ht (M+N))
    let B := ComplexRawQuotient.ofRaw (u (M+N)) (hu (M+N))
    change S=T+U at h
    change S+(A+B)=(T+A)+(U+B)
    generalize S=s,T=t,U=u,A=a,B=b at h ⊢
    grind only

theorem polynomialNomeDifferencePrefix_degree_3 (z : Scalar) (N : Nat) :
    (ScalarSeries.block (polynomialNomeDifferenceTerm z 3) 0 N).Equiv (add (sub (scaleRat 3 (polynomialNomeMomentPrefix z 2 N)) (scaleRat 3 (polynomialNomeMomentPrefix z 1 N))) (polynomialNomeMomentPrefix z 0 N)) := by
  have h3 : (ScalarSeries.block (fun n => (scaleRat 3 (polynomialNomeMomentTerm z 2 n))) 0 N).Equiv (scaleRat 3 (polynomialNomeMomentPrefix z 2 N)) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) 0 N)
      (scaleRat_valid (r := 3) (ScalarSeries.block_valid (fun n => (polynomialNomeMomentTerm z 2 n)) (fun n => (polynomialNomeMomentTerm_valid z 2 n)) 0 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N)) (representedBlock_scale (fun n => (polynomialNomeMomentTerm z 2 n)) (fun n => (polynomialNomeMomentTerm_valid z 2 n)) 3 0 N) (scaleRat_equiv (r := 3) (equiv_refl _ (polynomialNomeMomentPrefix_valid z 2 N)))
  have h4 : (ScalarSeries.block (fun n => (scaleRat 3 (polynomialNomeMomentTerm z 1 n))) 0 N).Equiv (scaleRat 3 (polynomialNomeMomentPrefix z 1 N)) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) 0 N)
      (scaleRat_valid (r := 3) (ScalarSeries.block_valid (fun n => (polynomialNomeMomentTerm z 1 n)) (fun n => (polynomialNomeMomentTerm_valid z 1 n)) 0 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 1 N)) (representedBlock_scale (fun n => (polynomialNomeMomentTerm z 1 n)) (fun n => (polynomialNomeMomentTerm_valid z 1 n)) 3 0 N) (scaleRat_equiv (r := 3) (equiv_refl _ (polynomialNomeMomentPrefix_valid z 1 N)))
  have h2 : (ScalarSeries.block (fun n => (sub (scaleRat 3 (polynomialNomeMomentTerm z 2 n)) (scaleRat 3 (polynomialNomeMomentTerm z 1 n)))) 0 N).Equiv (sub (scaleRat 3 (polynomialNomeMomentPrefix z 2 N)) (scaleRat 3 (polynomialNomeMomentPrefix z 1 N))) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n)))) 0 N)
      (sub_valid (ScalarSeries.block_valid (fun n => (scaleRat 3 (polynomialNomeMomentTerm z 2 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) 0 N) (ScalarSeries.block_valid (fun n => (scaleRat 3 (polynomialNomeMomentTerm z 1 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) 0 N)) (sub_valid (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 1 N))) (representedBlock_sub (fun n => (scaleRat 3 (polynomialNomeMomentTerm z 2 n))) (fun n => (scaleRat 3 (polynomialNomeMomentTerm z 1 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) 0 N) (FunctionTheory.sub_congr h3 h4)
  have h1 : (ScalarSeries.block (fun n => (add (sub (scaleRat 3 (polynomialNomeMomentTerm z 2 n)) (scaleRat 3 (polynomialNomeMomentTerm z 1 n))) (polynomialNomeMomentTerm z 0 n))) 0 N).Equiv (add (sub (scaleRat 3 (polynomialNomeMomentPrefix z 2 N)) (scaleRat 3 (polynomialNomeMomentPrefix z 1 N))) (polynomialNomeMomentPrefix z 0 N)) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) (polynomialNomeMomentTerm_valid z 0 n))) 0 N)
      (add_valid (ScalarSeries.block_valid (fun n => (sub (scaleRat 3 (polynomialNomeMomentTerm z 2 n)) (scaleRat 3 (polynomialNomeMomentTerm z 1 n)))) (fun n => (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n)))) 0 N) (ScalarSeries.block_valid (fun n => (polynomialNomeMomentTerm z 0 n)) (fun n => (polynomialNomeMomentTerm_valid z 0 n)) 0 N)) (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 1 N))) (polynomialNomeMomentPrefix_valid z 0 N)) (representedBlock_add (fun n => (sub (scaleRat 3 (polynomialNomeMomentTerm z 2 n)) (scaleRat 3 (polynomialNomeMomentTerm z 1 n)))) (fun n => (polynomialNomeMomentTerm z 0 n)) (fun n => (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n)))) (fun n => (polynomialNomeMomentTerm_valid z 0 n)) 0 N) (add_equiv h2 (equiv_refl _ (polynomialNomeMomentPrefix_valid z 0 N)))
  exact equiv_trans (ScalarSeries.block_valid _ (polynomialNomeDifferenceTerm_valid z 3) 0 N)
    (ScalarSeries.block_valid _ (fun n => (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) (polynomialNomeMomentTerm_valid z 0 n))) 0 N) (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 1 N))) (polynomialNomeMomentPrefix_valid z 0 N))
    (ScalarSeries.block_congr _ _ (fun n => polynomialNomeDifferenceTerm_degree_3 z n) 0 N) h1

theorem polynomialNomeDifferencePrefix_degree_4 (z : Scalar) (N : Nat) :
    (ScalarSeries.block (polynomialNomeDifferenceTerm z 4) 0 N).Equiv (sub (add (sub (scaleRat 4 (polynomialNomeMomentPrefix z 3 N)) (scaleRat 6 (polynomialNomeMomentPrefix z 2 N))) (scaleRat 4 (polynomialNomeMomentPrefix z 1 N))) (polynomialNomeMomentPrefix z 0 N)) := by
  have h4 : (ScalarSeries.block (fun n => (scaleRat 4 (polynomialNomeMomentTerm z 3 n))) 0 N).Equiv (scaleRat 4 (polynomialNomeMomentPrefix z 3 N)) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) 0 N)
      (scaleRat_valid (r := 4) (ScalarSeries.block_valid (fun n => (polynomialNomeMomentTerm z 3 n)) (fun n => (polynomialNomeMomentTerm_valid z 3 n)) 0 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 3 N)) (representedBlock_scale (fun n => (polynomialNomeMomentTerm z 3 n)) (fun n => (polynomialNomeMomentTerm_valid z 3 n)) 4 0 N) (scaleRat_equiv (r := 4) (equiv_refl _ (polynomialNomeMomentPrefix_valid z 3 N)))
  have h5 : (ScalarSeries.block (fun n => (scaleRat 6 (polynomialNomeMomentTerm z 2 n))) 0 N).Equiv (scaleRat 6 (polynomialNomeMomentPrefix z 2 N)) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) 0 N)
      (scaleRat_valid (r := 6) (ScalarSeries.block_valid (fun n => (polynomialNomeMomentTerm z 2 n)) (fun n => (polynomialNomeMomentTerm_valid z 2 n)) 0 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N)) (representedBlock_scale (fun n => (polynomialNomeMomentTerm z 2 n)) (fun n => (polynomialNomeMomentTerm_valid z 2 n)) 6 0 N) (scaleRat_equiv (r := 6) (equiv_refl _ (polynomialNomeMomentPrefix_valid z 2 N)))
  have h3 : (ScalarSeries.block (fun n => (sub (scaleRat 4 (polynomialNomeMomentTerm z 3 n)) (scaleRat 6 (polynomialNomeMomentTerm z 2 n)))) 0 N).Equiv (sub (scaleRat 4 (polynomialNomeMomentPrefix z 3 N)) (scaleRat 6 (polynomialNomeMomentPrefix z 2 N))) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n)))) 0 N)
      (sub_valid (ScalarSeries.block_valid (fun n => (scaleRat 4 (polynomialNomeMomentTerm z 3 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) 0 N) (ScalarSeries.block_valid (fun n => (scaleRat 6 (polynomialNomeMomentTerm z 2 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) 0 N)) (sub_valid (scaleRat_valid (polynomialNomeMomentPrefix_valid z 3 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N))) (representedBlock_sub (fun n => (scaleRat 4 (polynomialNomeMomentTerm z 3 n))) (fun n => (scaleRat 6 (polynomialNomeMomentTerm z 2 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) 0 N) (FunctionTheory.sub_congr h4 h5)
  have h6 : (ScalarSeries.block (fun n => (scaleRat 4 (polynomialNomeMomentTerm z 1 n))) 0 N).Equiv (scaleRat 4 (polynomialNomeMomentPrefix z 1 N)) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) 0 N)
      (scaleRat_valid (r := 4) (ScalarSeries.block_valid (fun n => (polynomialNomeMomentTerm z 1 n)) (fun n => (polynomialNomeMomentTerm_valid z 1 n)) 0 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 1 N)) (representedBlock_scale (fun n => (polynomialNomeMomentTerm z 1 n)) (fun n => (polynomialNomeMomentTerm_valid z 1 n)) 4 0 N) (scaleRat_equiv (r := 4) (equiv_refl _ (polynomialNomeMomentPrefix_valid z 1 N)))
  have h2 : (ScalarSeries.block (fun n => (add (sub (scaleRat 4 (polynomialNomeMomentTerm z 3 n)) (scaleRat 6 (polynomialNomeMomentTerm z 2 n))) (scaleRat 4 (polynomialNomeMomentTerm z 1 n)))) 0 N).Equiv (add (sub (scaleRat 4 (polynomialNomeMomentPrefix z 3 N)) (scaleRat 6 (polynomialNomeMomentPrefix z 2 N))) (scaleRat 4 (polynomialNomeMomentPrefix z 1 N))) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n)))) 0 N)
      (add_valid (ScalarSeries.block_valid (fun n => (sub (scaleRat 4 (polynomialNomeMomentTerm z 3 n)) (scaleRat 6 (polynomialNomeMomentTerm z 2 n)))) (fun n => (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n)))) 0 N) (ScalarSeries.block_valid (fun n => (scaleRat 4 (polynomialNomeMomentTerm z 1 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) 0 N)) (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentPrefix_valid z 3 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N))) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 1 N))) (representedBlock_add (fun n => (sub (scaleRat 4 (polynomialNomeMomentTerm z 3 n)) (scaleRat 6 (polynomialNomeMomentTerm z 2 n)))) (fun n => (scaleRat 4 (polynomialNomeMomentTerm z 1 n))) (fun n => (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n)))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) 0 N) (add_equiv h3 h6)
  have h1 : (ScalarSeries.block (fun n => (sub (add (sub (scaleRat 4 (polynomialNomeMomentTerm z 3 n)) (scaleRat 6 (polynomialNomeMomentTerm z 2 n))) (scaleRat 4 (polynomialNomeMomentTerm z 1 n))) (polynomialNomeMomentTerm z 0 n))) 0 N).Equiv (sub (add (sub (scaleRat 4 (polynomialNomeMomentPrefix z 3 N)) (scaleRat 6 (polynomialNomeMomentPrefix z 2 N))) (scaleRat 4 (polynomialNomeMomentPrefix z 1 N))) (polynomialNomeMomentPrefix z 0 N)) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (sub_valid (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) (polynomialNomeMomentTerm_valid z 0 n))) 0 N)
      (sub_valid (ScalarSeries.block_valid (fun n => (add (sub (scaleRat 4 (polynomialNomeMomentTerm z 3 n)) (scaleRat 6 (polynomialNomeMomentTerm z 2 n))) (scaleRat 4 (polynomialNomeMomentTerm z 1 n)))) (fun n => (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n)))) 0 N) (ScalarSeries.block_valid (fun n => (polynomialNomeMomentTerm z 0 n)) (fun n => (polynomialNomeMomentTerm_valid z 0 n)) 0 N)) (sub_valid (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentPrefix_valid z 3 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N))) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 1 N))) (polynomialNomeMomentPrefix_valid z 0 N)) (representedBlock_sub (fun n => (add (sub (scaleRat 4 (polynomialNomeMomentTerm z 3 n)) (scaleRat 6 (polynomialNomeMomentTerm z 2 n))) (scaleRat 4 (polynomialNomeMomentTerm z 1 n)))) (fun n => (polynomialNomeMomentTerm z 0 n)) (fun n => (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n)))) (fun n => (polynomialNomeMomentTerm_valid z 0 n)) 0 N) (FunctionTheory.sub_congr h2 (equiv_refl _ (polynomialNomeMomentPrefix_valid z 0 N)))
  exact equiv_trans (ScalarSeries.block_valid _ (polynomialNomeDifferenceTerm_valid z 4) 0 N)
    (ScalarSeries.block_valid _ (fun n => (sub_valid (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) (polynomialNomeMomentTerm_valid z 0 n))) 0 N) (sub_valid (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentPrefix_valid z 3 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N))) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 1 N))) (polynomialNomeMomentPrefix_valid z 0 N))
    (ScalarSeries.block_congr _ _ (fun n => polynomialNomeDifferenceTerm_degree_4 z n) 0 N) h1

theorem polynomialNomeDifferencePrefix_degree_5 (z : Scalar) (N : Nat) :
    (ScalarSeries.block (polynomialNomeDifferenceTerm z 5) 0 N).Equiv (add (sub (add (sub (scaleRat 5 (polynomialNomeMomentPrefix z 4 N)) (scaleRat 10 (polynomialNomeMomentPrefix z 3 N))) (scaleRat 10 (polynomialNomeMomentPrefix z 2 N))) (scaleRat 5 (polynomialNomeMomentPrefix z 1 N))) (polynomialNomeMomentPrefix z 0 N)) := by
  have h5 : (ScalarSeries.block (fun n => (scaleRat 5 (polynomialNomeMomentTerm z 4 n))) 0 N).Equiv (scaleRat 5 (polynomialNomeMomentPrefix z 4 N)) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n))) 0 N)
      (scaleRat_valid (r := 5) (ScalarSeries.block_valid (fun n => (polynomialNomeMomentTerm z 4 n)) (fun n => (polynomialNomeMomentTerm_valid z 4 n)) 0 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 4 N)) (representedBlock_scale (fun n => (polynomialNomeMomentTerm z 4 n)) (fun n => (polynomialNomeMomentTerm_valid z 4 n)) 5 0 N) (scaleRat_equiv (r := 5) (equiv_refl _ (polynomialNomeMomentPrefix_valid z 4 N)))
  have h6 : (ScalarSeries.block (fun n => (scaleRat 10 (polynomialNomeMomentTerm z 3 n))) 0 N).Equiv (scaleRat 10 (polynomialNomeMomentPrefix z 3 N)) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) 0 N)
      (scaleRat_valid (r := 10) (ScalarSeries.block_valid (fun n => (polynomialNomeMomentTerm z 3 n)) (fun n => (polynomialNomeMomentTerm_valid z 3 n)) 0 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 3 N)) (representedBlock_scale (fun n => (polynomialNomeMomentTerm z 3 n)) (fun n => (polynomialNomeMomentTerm_valid z 3 n)) 10 0 N) (scaleRat_equiv (r := 10) (equiv_refl _ (polynomialNomeMomentPrefix_valid z 3 N)))
  have h4 : (ScalarSeries.block (fun n => (sub (scaleRat 5 (polynomialNomeMomentTerm z 4 n)) (scaleRat 10 (polynomialNomeMomentTerm z 3 n)))) 0 N).Equiv (sub (scaleRat 5 (polynomialNomeMomentPrefix z 4 N)) (scaleRat 10 (polynomialNomeMomentPrefix z 3 N))) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n)))) 0 N)
      (sub_valid (ScalarSeries.block_valid (fun n => (scaleRat 5 (polynomialNomeMomentTerm z 4 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n))) 0 N) (ScalarSeries.block_valid (fun n => (scaleRat 10 (polynomialNomeMomentTerm z 3 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) 0 N)) (sub_valid (scaleRat_valid (polynomialNomeMomentPrefix_valid z 4 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 3 N))) (representedBlock_sub (fun n => (scaleRat 5 (polynomialNomeMomentTerm z 4 n))) (fun n => (scaleRat 10 (polynomialNomeMomentTerm z 3 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) 0 N) (FunctionTheory.sub_congr h5 h6)
  have h7 : (ScalarSeries.block (fun n => (scaleRat 10 (polynomialNomeMomentTerm z 2 n))) 0 N).Equiv (scaleRat 10 (polynomialNomeMomentPrefix z 2 N)) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) 0 N)
      (scaleRat_valid (r := 10) (ScalarSeries.block_valid (fun n => (polynomialNomeMomentTerm z 2 n)) (fun n => (polynomialNomeMomentTerm_valid z 2 n)) 0 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N)) (representedBlock_scale (fun n => (polynomialNomeMomentTerm z 2 n)) (fun n => (polynomialNomeMomentTerm_valid z 2 n)) 10 0 N) (scaleRat_equiv (r := 10) (equiv_refl _ (polynomialNomeMomentPrefix_valid z 2 N)))
  have h3 : (ScalarSeries.block (fun n => (add (sub (scaleRat 5 (polynomialNomeMomentTerm z 4 n)) (scaleRat 10 (polynomialNomeMomentTerm z 3 n))) (scaleRat 10 (polynomialNomeMomentTerm z 2 n)))) 0 N).Equiv (add (sub (scaleRat 5 (polynomialNomeMomentPrefix z 4 N)) (scaleRat 10 (polynomialNomeMomentPrefix z 3 N))) (scaleRat 10 (polynomialNomeMomentPrefix z 2 N))) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n)))) 0 N)
      (add_valid (ScalarSeries.block_valid (fun n => (sub (scaleRat 5 (polynomialNomeMomentTerm z 4 n)) (scaleRat 10 (polynomialNomeMomentTerm z 3 n)))) (fun n => (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n)))) 0 N) (ScalarSeries.block_valid (fun n => (scaleRat 10 (polynomialNomeMomentTerm z 2 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) 0 N)) (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentPrefix_valid z 4 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 3 N))) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N))) (representedBlock_add (fun n => (sub (scaleRat 5 (polynomialNomeMomentTerm z 4 n)) (scaleRat 10 (polynomialNomeMomentTerm z 3 n)))) (fun n => (scaleRat 10 (polynomialNomeMomentTerm z 2 n))) (fun n => (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n)))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) 0 N) (add_equiv h4 h7)
  have h8 : (ScalarSeries.block (fun n => (scaleRat 5 (polynomialNomeMomentTerm z 1 n))) 0 N).Equiv (scaleRat 5 (polynomialNomeMomentPrefix z 1 N)) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) 0 N)
      (scaleRat_valid (r := 5) (ScalarSeries.block_valid (fun n => (polynomialNomeMomentTerm z 1 n)) (fun n => (polynomialNomeMomentTerm_valid z 1 n)) 0 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 1 N)) (representedBlock_scale (fun n => (polynomialNomeMomentTerm z 1 n)) (fun n => (polynomialNomeMomentTerm_valid z 1 n)) 5 0 N) (scaleRat_equiv (r := 5) (equiv_refl _ (polynomialNomeMomentPrefix_valid z 1 N)))
  have h2 : (ScalarSeries.block (fun n => (sub (add (sub (scaleRat 5 (polynomialNomeMomentTerm z 4 n)) (scaleRat 10 (polynomialNomeMomentTerm z 3 n))) (scaleRat 10 (polynomialNomeMomentTerm z 2 n))) (scaleRat 5 (polynomialNomeMomentTerm z 1 n)))) 0 N).Equiv (sub (add (sub (scaleRat 5 (polynomialNomeMomentPrefix z 4 N)) (scaleRat 10 (polynomialNomeMomentPrefix z 3 N))) (scaleRat 10 (polynomialNomeMomentPrefix z 2 N))) (scaleRat 5 (polynomialNomeMomentPrefix z 1 N))) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (sub_valid (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n)))) 0 N)
      (sub_valid (ScalarSeries.block_valid (fun n => (add (sub (scaleRat 5 (polynomialNomeMomentTerm z 4 n)) (scaleRat 10 (polynomialNomeMomentTerm z 3 n))) (scaleRat 10 (polynomialNomeMomentTerm z 2 n)))) (fun n => (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n)))) 0 N) (ScalarSeries.block_valid (fun n => (scaleRat 5 (polynomialNomeMomentTerm z 1 n))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) 0 N)) (sub_valid (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentPrefix_valid z 4 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 3 N))) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N))) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 1 N))) (representedBlock_sub (fun n => (add (sub (scaleRat 5 (polynomialNomeMomentTerm z 4 n)) (scaleRat 10 (polynomialNomeMomentTerm z 3 n))) (scaleRat 10 (polynomialNomeMomentTerm z 2 n)))) (fun n => (scaleRat 5 (polynomialNomeMomentTerm z 1 n))) (fun n => (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n)))) (fun n => (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) 0 N) (FunctionTheory.sub_congr h3 h8)
  have h1 : (ScalarSeries.block (fun n => (add (sub (add (sub (scaleRat 5 (polynomialNomeMomentTerm z 4 n)) (scaleRat 10 (polynomialNomeMomentTerm z 3 n))) (scaleRat 10 (polynomialNomeMomentTerm z 2 n))) (scaleRat 5 (polynomialNomeMomentTerm z 1 n))) (polynomialNomeMomentTerm z 0 n))) 0 N).Equiv (add (sub (add (sub (scaleRat 5 (polynomialNomeMomentPrefix z 4 N)) (scaleRat 10 (polynomialNomeMomentPrefix z 3 N))) (scaleRat 10 (polynomialNomeMomentPrefix z 2 N))) (scaleRat 5 (polynomialNomeMomentPrefix z 1 N))) (polynomialNomeMomentPrefix z 0 N)) :=
    equiv_trans (ScalarSeries.block_valid _ (fun n => (add_valid (sub_valid (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) (polynomialNomeMomentTerm_valid z 0 n))) 0 N)
      (add_valid (ScalarSeries.block_valid (fun n => (sub (add (sub (scaleRat 5 (polynomialNomeMomentTerm z 4 n)) (scaleRat 10 (polynomialNomeMomentTerm z 3 n))) (scaleRat 10 (polynomialNomeMomentTerm z 2 n))) (scaleRat 5 (polynomialNomeMomentTerm z 1 n)))) (fun n => (sub_valid (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n)))) 0 N) (ScalarSeries.block_valid (fun n => (polynomialNomeMomentTerm z 0 n)) (fun n => (polynomialNomeMomentTerm_valid z 0 n)) 0 N)) (add_valid (sub_valid (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentPrefix_valid z 4 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 3 N))) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N))) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 1 N))) (polynomialNomeMomentPrefix_valid z 0 N)) (representedBlock_add (fun n => (sub (add (sub (scaleRat 5 (polynomialNomeMomentTerm z 4 n)) (scaleRat 10 (polynomialNomeMomentTerm z 3 n))) (scaleRat 10 (polynomialNomeMomentTerm z 2 n))) (scaleRat 5 (polynomialNomeMomentTerm z 1 n)))) (fun n => (polynomialNomeMomentTerm z 0 n)) (fun n => (sub_valid (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n)))) (fun n => (polynomialNomeMomentTerm_valid z 0 n)) 0 N) (add_equiv h2 (equiv_refl _ (polynomialNomeMomentPrefix_valid z 0 N)))
  exact equiv_trans (ScalarSeries.block_valid _ (polynomialNomeDifferenceTerm_valid z 5) 0 N)
    (ScalarSeries.block_valid _ (fun n => (add_valid (sub_valid (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentTerm_valid z 4 n)) (scaleRat_valid (polynomialNomeMomentTerm_valid z 3 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 2 n))) (scaleRat_valid (polynomialNomeMomentTerm_valid z 1 n))) (polynomialNomeMomentTerm_valid z 0 n))) 0 N) (add_valid (sub_valid (add_valid (sub_valid (scaleRat_valid (polynomialNomeMomentPrefix_valid z 4 N)) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 3 N))) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 2 N))) (scaleRat_valid (polynomialNomeMomentPrefix_valid z 1 N))) (polynomialNomeMomentPrefix_valid z 0 N))
    (ScalarSeries.block_congr _ _ (fun n => polynomialNomeDifferenceTerm_degree_5 z n) 0 N) h1

end ComputableAnalysis.ModularForms
