import ComputableAnalysis.Basel.RealZeta
import ComputableAnalysis.ZetaReal.Tests

#print axioms ComputableAnalysis.ZetaReal.coefficient_step
#print axioms ComputableAnalysis.ZetaReal.magnitude_decay
#print axioms ComputableAnalysis.ZetaReal.moment_bound
#print axioms ComputableAnalysis.ZetaReal.rectangle_outer_tail
#print axioms ComputableAnalysis.ZetaReal.rectangle_inner_tail
#print axioms ComputableAnalysis.ZetaReal.outerBudget_dyadic_shrinks
#print axioms ComputableAnalysis.ZetaReal.approx_cauchy
#print axioms ComputableAnalysis.ZetaReal.raw_valid
#print axioms ComputableAnalysis.ZetaReal.continuous
#print axioms ComputableAnalysis.ZetaReal.domainReal_inChart
#print axioms ComputableAnalysis.ZetaReal.zeta_valid
#print axioms ComputableAnalysis.ZetaReal.zeta_equiv
#print axioms ComputableAnalysis.ZetaReal.raw_chart_equiv
#print axioms ComputableAnalysis.ZetaReal.binomial_equation
#print axioms ComputableAnalysis.ZetaReal.binomial_unique
#print axioms ComputableAnalysis.ZetaReal.rectangle_dirichlet
#print axioms ComputableAnalysis.ZetaReal.dirichletRaw_valid
#print axioms ComputableAnalysis.ZetaReal.inversePowerRaw_valid
#print axioms ComputableAnalysis.ZetaReal.inversePowerRaw_enclosure
#print axioms ComputableAnalysis.ZetaReal.dirichlet_convergence
#print axioms ComputableAnalysis.ZetaReal.zeta_integer_equiv
#print axioms ComputableAnalysis.ZetaReal.zeta_three_equiv
#print axioms ComputableAnalysis.ZetaReal.Tests.threeHalves_coefficient
#print axioms ComputableAnalysis.ZetaReal.Tests.threeHalves_rectangle
#print axioms ComputableAnalysis.ZetaReal.Tests.delayedThree_same_zeta

#print axioms ComputableAnalysis.Basel.leibniz_square_error
#print axioms ComputableAnalysis.Basel.zeta_leibniz_square_budget
#print axioms ComputableAnalysis.Basel.eulerBasel
#print axioms ComputableAnalysis.Basel.EulerSieve.sieve_cons
#print axioms ComputableAnalysis.Basel.EulerSieve.sieve_error
#print axioms ComputableAnalysis.Basel.zetaTwo_equiv_finiteEulerProduct
#print axioms ComputableAnalysis.Basel.prime_unbounded_of_piSquare_irrational
#print axioms ComputableAnalysis.Basel.real_zeta_two_equiv_piSquaredOverSix
