#!/usr/bin/env python3
"""Render exact rational stages of a single-turn integral split.

The example is `f(t) = 4 - (t^2 - 2)^2` on `[0, 2]`.  It increases up to
the irrational turning point `sqrt(2)` and decreases afterwards.  The frames
use the rational secant--tangent brackets generated by the square-root
algorithm.  The middle rectangle is the literal bounded contribution
`(right - left) * [0, 4]`; the outside regions are the two certified monotone
pieces of the construction pattern.
"""

from __future__ import annotations

from fractions import Fraction
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "blueprint" / "src" / "assets"
GIF_PATH = ASSET_DIR / "single-turn-integral.gif"
PNG_PATH = ASSET_DIR / "single-turn-integral.png"

WIDTH, HEIGHT = 700, 500
LEFT, RIGHT = 82, 642
TOP, BASELINE = 50, 390
WHITE = (255, 255, 255, 255)
INK = (28, 41, 56, 255)
AXIS = (100, 116, 139, 255)
GRID = (203, 213, 225, 255)
CURVE = (30, 64, 175, 255)
LEFT_FILL = (176, 227, 219, 210)
LEFT_EDGE = (13, 148, 136, 255)
RIGHT_FILL = (254, 215, 170, 210)
RIGHT_EDGE = (234, 88, 12, 255)
MIDDLE_FILL = (253, 230, 138, 135)
MIDDLE_EDGE = (202, 138, 4, 255)


def font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    for name in (
        "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/Library/Fonts/Arial.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ):
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    return ImageFont.load_default()


SMALL = font(16)
LABEL = font(18)


def x_screen(t: Fraction) -> float:
    return LEFT + float(t / 2) * (RIGHT - LEFT)


def y_screen(value: Fraction) -> float:
    return BASELINE - float(value / 4) * (BASELINE - TOP)


def value(t: Fraction) -> Fraction:
    return 4 - (t * t - 2) * (t * t - 2)


def next_bracket(left: Fraction, right: Fraction) -> tuple[Fraction, Fraction]:
    return (2 + left * right) / (left + right), (right + 2 / right) / 2


def bracket_states() -> list[tuple[Fraction, Fraction]]:
    left, right = Fraction(1), Fraction(2)
    result = []
    for _ in range(4):
        result.append((left, right))
        left, right = next_bracket(left, right)
    return result


def filled_curve_region(
    draw: ImageDraw.ImageDraw, start: Fraction, stop: Fraction, fill: tuple[int, int, int, int]
) -> None:
    count = 120
    points = [(x_screen(start), BASELINE)]
    for index in range(count + 1):
        t = start + (stop - start) * Fraction(index, count)
        points.append((x_screen(t), y_screen(value(t))))
    points.append((x_screen(stop), BASELINE))
    draw.polygon(points, fill=fill)


def frame(left: Fraction, right: Fraction) -> Image.Image:
    image = Image.new("RGBA", (WIDTH, HEIGHT), WHITE)
    draw = ImageDraw.Draw(image)

    for half in range(1, 4):
        x = x_screen(Fraction(half, 2))
        draw.line((x, TOP, x, BASELINE), fill=GRID, width=1)
    for value_y in range(1, 4):
        y = y_screen(Fraction(value_y))
        draw.line((LEFT, y, RIGHT, y), fill=GRID, width=1)

    draw.line((LEFT - 25, BASELINE, RIGHT + 26, BASELINE), fill=AXIS, width=3)
    draw.line((LEFT, BASELINE + 18, LEFT, TOP - 18), fill=AXIS, width=3)

    filled_curve_region(draw, Fraction(0), left, LEFT_FILL)
    filled_curve_region(draw, right, Fraction(2), RIGHT_FILL)
    draw.rectangle(
        (x_screen(left), y_screen(Fraction(4)), x_screen(right), BASELINE),
        fill=MIDDLE_FILL,
        outline=MIDDLE_EDGE,
        width=3,
    )

    points = []
    for index in range(401):
        t = Fraction(2 * index, 400)
        points.append((x_screen(t), y_screen(value(t))))
    draw.line(points, fill=CURVE, width=4, joint="curve")

    for tick, label in ((Fraction(0), "0"), (Fraction(1), "1"), (Fraction(2), "2")):
        x = x_screen(tick)
        draw.line((x, BASELINE - 7, x, BASELINE + 7), fill=AXIS, width=2)
        draw.text((x, BASELINE + 30), label, font=SMALL, fill=INK, anchor="mm")
    for tick, label in ((Fraction(2), "2"), (Fraction(4), "4")):
        y = y_screen(tick)
        draw.line((LEFT - 7, y, LEFT + 7, y), fill=AXIS, width=2)
        draw.text((LEFT - 16, y), label, font=SMALL, fill=INK, anchor="rm")

    left_x, right_x = x_screen(left), x_screen(right)
    draw.line((left_x, TOP, left_x, BASELINE), fill=MIDDLE_EDGE, width=2)
    draw.line((right_x, TOP, right_x, BASELINE), fill=MIDDLE_EDGE, width=2)
    draw.text((left_x - 9, BASELINE + 54), "l", font=SMALL, fill=MIDDLE_EDGE, anchor="rm")
    draw.text((right_x + 9, BASELINE + 54), "r", font=SMALL, fill=MIDDLE_EDGE, anchor="lm")
    draw.text((RIGHT + 22, BASELINE + 4), "t", font=LABEL, fill=INK, anchor="lm")
    draw.text((LEFT - 2, TOP - 20), "f", font=LABEL, fill=INK, anchor="mm")
    return image


def main() -> None:
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    frames = [frame(left, right) for left, right in bracket_states()]
    # The second bracket displays both certified monotone tails and the middle box.
    frames[1].save(PNG_PATH, format="PNG", optimize=True)
    frames[0].save(
        GIF_PATH,
        format="GIF",
        save_all=True,
        append_images=frames[1:],
        duration=[1250, 1250, 1250, 1900],
        loop=0,
        disposal=2,
        optimize=True,
    )
    print(f"wrote {GIF_PATH.relative_to(ROOT)}")
    print(f"wrote {PNG_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
